<?php 
// 合并配置文件后生成的文件
return 

[
    'vendorPath'=>'D:\ding\wamp64\www\yii\fecshop/vendor',
    'components'=>
    [
        'urlManager'=>
        [
            'class'=>'yii\web\UrlManager',
            'enablePrettyUrl'=>true,
            'showScriptName'=>false,
            'rules'=>
            [
                ''=>'cms/home/index',// 路由规则,默认入口文件，也可可以通过defaultRoute
            ],
        ],
        'assetManager'=>
        [
            'forceCopy'=>false,
        ],
        'db'=>
        [
            'class'=>'yii\db\Connection',
            'dsn'=>'mysql:host=118.25.38.240;dbname=fecshop_test',
            'username'=>'fecshop_test',
            'password'=>'888888',
            'charset'=>'utf8',
        ],
        // 配置的mongodb数据库
        'mongodb'=>
        [
            'class'=>'yii\mongodb\Connection',
            'dsn'=>'mongodb://simpleUser:simplePass@118.25.38.240:27017/fecshop_test',
        ],
        'redis'=>
        [
            'class'=>'yii\redis\Connection',
            'hostname'=>'118.25.38.240',
            'port'=>6379,
            'database'=>0,
        ],
        'cache'=>
        [
            'class'=>'yii\redis\Cache',
            'redis'=>
            [
                'hostname'=>'118.25.38.240',
                'port'=>6379,
                'database'=>6,// 使用的redis数据库
            ],
            'keyPrefix'=>'appfront_cache',
        ],
        'session'=>
        [
            'class'=>'yii\redis\Session',
            'timeout'=>604800,
            'redis'=>
            [
                'hostname'=>'118.25.38.240',
                'port'=>6379,
                'database'=>5,
            ],
            'keyPrefix'=>'appfront_session',
        ],
        'i18n'=>
        [
            'translations'=>
            [
                'appfront'=>
                [
                    'basePaths'=>
                    [
                        0=>'@appfront/languages',
                        1=>'@fecshop/app/appfront/languages',
                    ],
                    'sourceLanguage'=>'en_US',
                    'class'=>'fecshop\yii\i18n\PhpMessageSource',
                ],
            ],
        ],
        'log'=>
        [
            'traceLevel'=>3,
            'flushInterval'=>1,
            'targets'=>
            [
                'file'=>
                [
                    'categories'=>
                    [
                        0=>'fecshop_debug',
                    ],
                    'class'=>'yii\log\FileTarget',
                    'exportInterval'=>1,
                    'logFile'=>'@appfront/runtime/fecshop_logs/fecshop_debug.log',
                    'prefix' => function ($message) {
                        return $message;
                    },
                    'logVars'=>
                    [

                    ],
                ],
            ],
        ],
        'request'=>
        [
            'cookieValidationKey'=>'FoOwzm-NS4xrnCPaCEhUP0QYOmnAdHjL',
            'class'=>'fecshop\yii\web\Request',
        ],
        // 记录service运行时间的日志组件
        'serviceLog'=>
        [
            'class'=>'fecshop\components\ServiceLog',
            'log_config'=>
            [
                'services'=>
                [
                    'enable'=>false,
                    'dbprint'=>false,
                    'htmlprint'=>false,
                    'htmlprintbyparam'=>
                    [
                        'enable'=>false,
                        'paramKey'=>'servicelog',
                        'paramVal'=>'xxxxxxxx',
                    ],
                ],
            ],
        ],
        'store'=>
        [
            'class'=>'fecshop\components\Store',
        ],
        'xunsearch'=>
        [
            'class'=>'hightman\xunsearch\Connection',
            'iniDirectory'=>'@fecshop/config/xunsearch',
            'charset'=>'utf-8',
        ],
        'user'=>
        [
            'class'=>'fecshop\yii\web\User',
            'identityClass'=>'fecshop\models\mysqldb\Customer',
            'enableAutoLogin'=>true,
        ],
        'errorHandler'=>
        [
            'errorAction'=>'site/helper/error',
        ],
    ],
    'id'=>'app-front',
    'timeZone'=>'Asia/Shanghai', // 时区
    'basePath'=>'D:\ding\wamp64\www\yii\fecshop\appfront',
    'controllerNamespace'=>'appfront\controllers',
    'params'=>
    [
        'appfrontBaseTheme'=>'@fecshop/app/appfront/theme/base/front', # fecshop自带的模板路径
        'appfrontBaseLayoutName'=>'main.php', # layout文件配置
        'appName'=>'appfront',
    ],
    'bootstrap'=>
    [
        0=>'debug',
        1=>'gii',
        // 预先加载store, 执行store的Bootstrap方法
        2=>'store',
    ],
    'modules'=>
    [
        'debug'=>'yii\debug\Module',
        'gii'=>'yii\gii\Module',
        'catalog'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Catalog\Module',
            'params'=>
            [
                'category_breadcrumbs'=>false,
                'category_filter_attr'=>
                [
                    0=>'color',
                    1=>'size',
                ],
                'category_filter_category'=>true,
                'category_filter_price'=>true,
                'category_query'=>
                [
                    'numPerPage'=>
                    [
                        0=>30,
                        1=>60,
                        2=>90,
                    ],
                    'sort'=>
                    [
                        'hot'=>
                        [
                            'label'=>'Hot',
                            'db_columns'=>'score',
                            'direction'=>'desc',
                        ],
                        'review_count'=>
                        [
                            'label'=>'Review',
                            'db_columns'=>'review_count',
                            'direction'=>'desc',
                        ],
                        'favorite_count'=>
                        [
                            'label'=>'Favorite',
                            'db_columns'=>'favorite_count',
                            'direction'=>'desc',
                        ],
                        'new'=>
                        [
                            'label'=>'New',
                            'db_columns'=>'created_at',
                            'direction'=>'desc',
                        ],
                        'stock'=>
                        [
                            'label'=>'Stock',
                            'db_columns'=>'qty',
                            'direction'=>'desc',
                        ],
                        'low-to-high'=>
                        [
                            'label'=>'$ Low to High',
                            'db_columns'=>'final_price',
                            'direction'=>'asc',
                        ],
                        'high-to-low'=>
                        [
                            'label'=>'$ High to Low',
                            'db_columns'=>'final_price',
                            'direction'=>'desc',
                        ],
                    ],
                    'price_range'=>
                    [
                        0=>'0-10',
                        1=>'10-20',
                        2=>'20-30',
                        3=>'30-50',
                        4=>'50-100',
                        5=>'100-150',
                        6=>'150-300',
                        7=>'300-500',
                        8=>'500-1000',
                        9=>'1000-',
                    ],
                ],
                'productImgSize'=>
                [
                    'small_img_width'=>80,
                    'small_img_height'=>110,
                    'middle_img_width'=>400,
                ],
                'productImgMagnifier'=>false,
                'review'=>
                [
                    'add_captcha'=>true,
                    'productPageReviewCount'=>10,
                    'reviewPageReviewCount'=>20,
                    'addReviewOnlyLogin'=>true,
                    'ifShowCurrentUserNoAuditReview'=>true,
                    'filterByLang'=>true,
                ],
                'favorite'=>
                [
                    'addSuccessRedirectFavoriteList'=>false,
                ],
            ],
        ],
        'catalogsearch'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Catalogsearch\Module',
            'params'=>
            [
                'search_page_title_format'=>'Search Text: %s ',
                'search_page_meta_keywords_format'=>'Search Text: %s ',
                'search_page_meta_description_format'=>'Search Text: %s ',
                'product_search_max_count'=>1000,
                'search_breadcrumbs'=>true,
                'search_query'=>
                [
                    'numPerPage'=>
                    [
                        0=>30,
                        1=>60,
                        2=>90,
                    ],
                    'price_range'=>
                    [
                        0=>'0-10',
                        1=>'10-20',
                        2=>'20-30',
                        3=>'30-50',
                        4=>'50-100',
                        5=>'100-150',
                        6=>'150-300',
                        7=>'300-500',
                        8=>'500-1000',
                        9=>'1000-',
                    ],
                ],
            ],
        ],
        'checkout'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Checkout\Module',
            'params'=>
            [
                'guestOrder'=>true,
            ],
        ],
        'cms'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Cms\Module',
            'params'=>
            [
                'home_title'=>
                [
                    'home_title_en'=>'Fecshop Home Page En',
                    'home_title_zh'=>'Fecshop Home Page Zh',
                    'home_title_fr'=>'Fecshop Home Page Fr',
                    'home_title_es'=>'Fecshop Home Page Es',
                ],
                'home_meta_keywords'=>
                [
                    'home_meta_keywords_en'=>'Fecshop , Fashion E-Commerce Shop En',
                    'home_meta_keywords_zh'=>'Fecshop , Fashion E-Commerce Shop Zh',
                    'home_meta_keywords_fr'=>'Fecshop , Fashion E-Commerce Shop Fr',
                    'home_meta_keywords_es'=>'Fecshop , Fashion E-Commerce Shop Es',
                ],
                'home_meta_description'=>
                [
                    'home_meta_description_en'=>'Fashion E-Commerce Shop , Base On Yii2 Framework En',
                    'home_meta_description_zh'=>'Fashion E-Commerce Shop , Base On Yii2 Framework Zh',
                    'home_meta_description_fr'=>'Fashion E-Commerce Shop , Base On Yii2 Framework Fr',
                    'home_meta_description_es'=>'Fashion E-Commerce Shop , Base On Yii2 Framework Es',
                ],
                'homeBestSellerSku'=>
                [
                    0=>'p10001-kahaki-xl',
                    1=>'sk10003-001',
                    2=>'sk10005',
                    3=>'sk1000-khak',
                    4=>'sk0003',
                    5=>'men0003',
                    6=>'men0002',
                    7=>'men0001',
                ],
                'homeFeaturedSku'=>
                [
                    0=>'men0003',
                    1=>'men0002',
                    2=>'men0001',
                    3=>'computer001-xinghao2-cpu3',
                    4=>'22221',
                    5=>'sk10005',
                    6=>'sk1000-khak',
                    7=>'222212',
                ],
            ],
        ],
        'customer'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Customer\Module',
            'params'=>
            [
                'register'=>
                [
                    'successAutoLogin'=>true,
                    'loginSuccessRedirectUrlKey'=>'customer/account',
                    'registerPageCaptcha'=>true,
                ],
                'login'=>
                [
                    'loginPageSuccessRedirectUrlKey'=>'customer/account',
                    'otherPageSuccessRedirectUrlKey'=>false,
                    'loginPageCaptcha'=>false,
                ],
                'forgotPassword'=>
                [
                    'forgotCaptcha'=>true,
                ],
                'leftMenu'=>
                [
                    'Account Dashboard'=>'customer/account',
                    'Account Information'=>'customer/editaccount',
                    'Address Book'=>'customer/address',
                    'My Orders'=>'customer/order',
                    'My Product Reviews'=>'customer/productreview',
                    'My Favorite'=>'customer/productfavorite',
                ],
                'contacts'=>
                [
                    'contactsCaptcha'=>true,
                ],
                'newsletterSubscribe'=>
                [

                ],
            ],
        ],
        'payment'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Payment\Module',
            'params'=>
            [

            ],
        ],
        'site'=>
        [
            'class'=>'\fecshop\app\appfront\modules\Site\Module',
            'params'=>
            [

            ],
        ],
        'mytest'=>
        [
            'class'=>'\appfront\local\local_modules\Mytest\Module',
        ],
    ],
    // 服务
    'services'=>
    [
        'adminUser'=>
        [
            'class'=>'fecshop\services\AdminUser',
        ],
        'cache'=>
        [
            'class'=>'fecshop\services\Cache',
            'enable'=>false,
            'cacheConfig'=>
            [
                'category'=>
                [
                    'enable'=>true,
                    'timeout'=>3600,
                    'disableUrlParam'=>'fecshop',
                    'cacheUrlParam'=>
                    [
                        0=>'p',
                        1=>'dir',
                        2=>'sort',
                        3=>'numPerPage',
                        4=>'price',
                        5=>'size',
                        6=>'color',
                        7=>'style',
                        8=>'dresses-length',
                        9=>'pattern-type',
                        10=>'collar',
                        11=>'xinghao',
                        12=>'cpu',
                    ],
                ],
                'product'=>
                [
                    'enable'=>true,
                    'timeout'=>3600,
                    'disableUrlParam'=>'fecshop',
                ],
                'home'=>
                [
                    'enable'=>true,
                    'timeout'=>3600,
                    'disableUrlParam'=>'fecshop',
                ],
                'article'=>
                [
                    'enable'=>true,
                    'timeout'=>3600,
                    'disableUrlParam'=>'fecshop',
                ],
            ],
        ],
        'cart'=>
        [
            'class'=>'fecshop\services\Cart',
            'childService'=>
            [
                'quote'=>
                [
                    'class'=>'fecshop\services\cart\Quote',
                ],
                'quoteItem'=>
                [
                    'class'=>'fecshop\services\cart\QuoteItem',
                ],
                'info'=>
                [
                    'class'=>'fecshop\services\cart\Info',
                    'maxCountAddToCart'=>100,
                    'addToCartCheckSkuQty'=>false,
                ],
                'coupon'=>
                [
                    'class'=>'fecshop\services\cart\Coupon',
                ],
            ],
        ],
        'category'=>
        [
            'class'=>'fecshop\services\Category',
            'childService'=>
            [
                'product'=>
                [
                    'class'=>'fecshop\services\category\Product',
                ],
                'menu'=>
                [
                    'class'=>'fecshop\services\category\Menu',
                ],
                'image'=>
                [
                    'class'=>'fecshop\services\category\Image',
                    'imageFloder'=>'media/catalog/category',
                    'maxUploadMSize'=>5,
                ],
            ],
        ],
        'cms'=>
        [
            'class'=>'fecshop\services\Cms',
            'childService'=>
            [
                'article'=>
                [
                    'class'=>'fecshop\services\cms\Article',
                    'storage'=>'ArticleMysqldb',
                ],
                'staticblock'=>
                [
                    'class'=>'fecshop\services\cms\StaticBlock',
                    'storage'=>'StaticBlockMongodb',
                ],
            ],
        ],
        'customer'=>
        [
            'class'=>'fecshop\services\Customer',
            'customer_register'=>
            [
                'min_name_length'=>1,
                'max_name_length'=>30,
                'min_pass_length'=>6,
                'max_pass_length'=>30,
            ],
            'childService'=>
            [
                'newsletter'=>
                [
                    'class'=>'fecshop\services\customer\Newsletter',
                ],
                'address'=>
                [
                    'class'=>'fecshop\services\customer\Address',
                ],
                'affiliate'=>
                [
                    'class'=>'fecshop\services\customer\Affiliate',
                ],
                'coupon'=>
                [
                    'class'=>'fecshop\services\customer\Coupon',
                ],
                'dropship'=>
                [
                    'class'=>'fecshop\services\customer\Dropship',
                ],
                'favorite'=>
                [
                    'class'=>'fecshop\services\customer\Favorite',
                ],
                'message'=>
                [
                    'class'=>'fecshop\services\customer\Message',
                ],
                'order'=>
                [
                    'class'=>'fecshop\services\customer\Order',
                ],
                'point'=>
                [
                    'class'=>'fecshop\services\customer\Point',
                ],
                'review'=>
                [
                    'class'=>'fecshop\services\customer\Review',
                ],
                'wholesale'=>
                [
                    'class'=>'fecshop\services\customer\Wholesale',
                ],
                'facebook'=>
                [
                    'class'=>'fecshop\services\customer\Facebook',
                ],
                'google'=>
                [
                    'class'=>'fecshop\services\customer\Google',
                ],
            ],
        ],
        'email'=>
        [
            'class'=>'fecshop\services\Email',
            'mailerInfo'=>
            [
                'storeName'=>'FecShop',
                'phone'=>'xxxxxxxxxx',
                'contacts'=>
                [
                    'emailAddress'=>'2358269014@qq.com',
                ],
            ],
            'childService'=>
            [
                'customer'=>
                [
                    'class'=>'fecshop\services\email\Customer',
                    'emailTheme'=>
                    [
                        'register'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\customer\account\register\Body',
                            'viewPath'=>'@fecshop/services/email/views/customer/account/register',
                            'mailerConfig'=>'default',
                        ],
                        'login'=>
                        [
                            'enable'=>false,
                            'widget'=>'fecshop\services\email\widgets\customer\account\login\Body',
                            'viewPath'=>'@fecshop/services/email/views/customer/account/login',
                            'mailerConfig'=>'default',
                        ],
                        'forgotPassword'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\customer\account\forgotpassword\Body',
                            'viewPath'=>'@fecshop/services/email/views/customer/account/forgotpassword',
                            'passwordResetTokenExpire'=>86400,
                            'mailerConfig'=>'default',
                        ],
                        'contacts'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\customer\contacts\Body',
                            'viewPath'=>'@fecshop/services/email/views/customer/contacts',
                            'address'=>'2358269014@qq.com',
                        ],
                        'newsletter'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\customer\newsletter\Body',
                            'viewPath'=>'@fecshop/services/email/views/customer/newsletter',
                            'mailerConfig'=>'default',
                        ],
                    ],
                ],
                'order'=>
                [
                    'class'=>'fecshop\services\email\Order',
                    'emailTheme'=>
                    [
                        'guestCreate'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\order\create\Body',
                            'viewPath'=>'@fecshop/services/email/views/order/create/guest',
                            'mailerConfig'=>'default',
                        ],
                        'loginedCreate'=>
                        [
                            'enable'=>true,
                            'widget'=>'fecshop\services\email\widgets\order\create\Body',
                            'viewPath'=>'@fecshop/services/email/views/order/create/logined',
                            'mailerConfig'=>'default',
                        ],
                    ],
                ],
            ],
            'mailerConfig'=>
            [
                'default'=>
                [
                    'class'=>'yii\swiftmailer\Mailer',
                    'transport'=>
                    [
                        'class'=>'Swift_SmtpTransport',
                        'host'=>'smtp.qq.com',
                        'username'=>'2420577683@qq.com',
                        'password'=>'fqeaizkpwbbvebeg',
                        'port'=>'587',
                        'encryption'=>'tls',
                    ],
                    'messageConfig'=>
                    [
                        'charset'=>'UTF-8',
                    ],
                ],
            ],
        ],
        'event'=>
        [
            'class'=>'fecshop\services\Event',
            'eventList'=>
            [
                'event_add_to_cart_before'=>
                [

                ],
                'event_add_to_cart_after'=>
                [

                ],
                'event_generate_order_before'=>
                [

                ],
                'event_generate_order_after'=>
                [

                ],
            ],
        ],
        'fecshoplang'=>
        [
            'class'=>'fecshop\services\FecshopLang',
            // 语言缩写对应的简码
            'allLangCode'=>
            [
                'en_US'=>
                [
                    'code'=>'en',
                ],
                'fr_FR'=>
                [
                    'code'=>'fr',
                ],
                'de_DE'=>
                [
                    'code'=>'de',
                ],
                'es_ES'=>
                [
                    'code'=>'es',
                ],
                'ru_RU'=>
                [
                    'code'=>'ru',
                ],
                'pt_PT'=>
                [
                    'code'=>'pt',
                ],
                'zh_CN'=>
                [
                    'code'=>'zh',
                ],
                'it_IT'=>
                [
                    'code'=>'it',
                ],
            ],
            'defaultLangCode'=>'en',
        ],
        'helper'=>
        [
            'class'=>'fecshop\services\Helper',
            'childService'=>
            [
                'ar'=>
                [
                    'class'=>'fecshop\services\helper\AR',
                ],
                'errors'=>
                [
                    'class'=>'fecshop\services\helper\Errors',
                ],
                'errorHandler'=>
                [
                    'class'=>'fecshop\services\helper\ErrorHandler',
                ],
                'mobileDetect'=>
                [
                    'class'=>'fecshop\services\helper\MobileDetect',
                ],
                'captcha'=>
                [
                    'class'=>'fecshop\services\helper\Captcha',
                    'charset'=>'023456789',
                    'codelen'=>4,
                    'width'=>130,
                    'height'=>50,
                    'fontsize'=>20,
                    'case_sensitive'=>false,
                ],
                'country'=>
                [
                    'class'=>'fecshop\services\helper\Country',
                ],
                'format'=>
                [
                    'class'=>'fecshop\services\helper\Format',
                ],
                'appserver'=>
                [
                    'class'=>'fecshop\services\helper\Appserver',
                ],
                'appapi'=>
                [
                    'class'=>'fecshop\services\helper\Appapi',
                ],
                'echart'=>
                [
                    'class'=>'fecshop\services\helper\Echart',
                ],
            ],
        ],
        'image'=>
        [
            'class'=>'fecshop\services\Image',
            'appbase'=>
            [
                'appfront'=>
                [
                    'basedir'=>'@appimage/appfront',
                    'basedomain'=>'//img3.fecshoptest.com',
                ],
                'apphtml5'=>
                [
                    'basedir'=>'@appimage/apphtml5',
                    'basedomain'=>'//img2.fecshoptest.com',
                ],
                'appadmin'=>
                [
                    'basedir'=>'@appimage/appadmin',
                    'basedomain'=>'//img2.fecshoptest.com',
                ],
                'common'=>
                [
                    'basedir'=>'@appimage/common',
                    'basedomain'=>'//img.fecshoptest.com',
                ],
            ],
        ],
        'order'=>
        [
            'class'=>'fecshop\services\Order',
            'childService'=>
            [
                'item'=>
                [
                    'class'=>'fecshop\services\order\Item',
                ],
            ],
            'increment_id'=>'1100000000',
            'requiredAddressAttr'=>
            [
                0=>'first_name',
                1=>'last_name',
                2=>'email',
                3=>'telephone',
                4=>'street1',
                5=>'country',
                6=>'city',
                7=>'state',
                8=>'zip',
            ],
            'minuteBeforeThatReturnPendingStock'=>600,
            'orderCountThatReturnPendingStock'=>30,
            'payment_status_pending'=>'payment_pending',
            'payment_status_processing'=>'payment_processing',
            'payment_status_confirmed'=>'payment_confirmed',
            'payment_status_suspected_fraud'=>'payment_suspected_fraud',
            'payment_status_canceled'=>'payment_canceled',
            'status_holded'=>'holded',
            'status_processing'=>'processing',
            'status_dispatched'=>'dispatched',
            'status_refunded'=>'refunded',
            'status_completed'=>'completed',
        ],
        'page'=>
        [
            'class'=>'fecshop\services\Page',
            'childService'=>
            [
                'breadcrumbs'=>
                [
                    'class'=>'fecshop\services\page\Breadcrumbs',
                    'homeName'=>'Home',
                    'ifAddHomeUrl'=>true,
                ],
                'translate'=>
                [
                    'class'=>'fecshop\services\page\Translate',
                ],
                'asset'=>
                [
                    'class'=>'fecshop\services\page\Asset',
                    'jsVersion'=>2,
                    'cssVersion'=>2,
                    'basePath'=>'@webroot/assets',
                    'baseUrl'=>'@web/assets',
                    'forceCopy'=>true,
                ],
                // 主题
                'theme'=>
                [
                    'class'=>'fecshop\services\page\Theme',
                ],
                'widget'=>
                [
                    'class'=>'fecshop\services\page\Widget',
                    'widgetConfig'=>
                    [
                        'head'=>
                        [
                            'class'=>'fecshop\app\appfront\widgets\Head',
                            'view'=>'widgets/head.php',
                            'cache'=>
                            [
                                'enable'=>false,
                                'timeout'=>4500,
                            ],
                        ],
                        'header'=>
                        [
                            'class'=>'fecshop\app\appfront\widgets\Headers',
                            'view'=>'widgets/header.php',
                            'cache'=>
                            [
                                'enable'=>false,
                                'timeout'=>4500,
                            ],
                        ],
                        'topsearch'=>
                        [
                            'view'=>'widgets/topsearch.php',
                        ],
                        'menu'=>
                        [
                            'class'=>'fecshop\app\appfront\widgets\Menu',
                            'view'=>'widgets/menu.php',
                            'cache'=>
                            [
                                'enable'=>false,
                            ],
                        ],
                        'footer'=>
                        [
                            'class'=>'fecshop\app\appfront\widgets\Footer',
                            'view'=>'widgets/footer.php',
                            'cache'=>
                            [
                                'enable'=>false,
                            ],
                        ],
                        'scroll'=>
                        [
                            'view'=>'widgets/scroll.php',
                        ],
                        'breadcrumbs'=>
                        [
                            'view'=>'widgets/breadcrumbs.php',
                        ],
                        'flashmessage'=>
                        [
                            'view'=>'widgets/flashmessage.php',
                        ],
                        'trace'=>
                        [
                            'view'=>'widgets/trace.php',
                        ],
                        'beforeContent'=>
                        [
                            'view'=>'widgets/beforeContent.php',
                        ],
                    ],
                ],
                'currency'=>
                [
                    'class'=>'fecshop\services\page\Currency',
                    'baseCurrecy'=>'USD',
                    'defaultCurrency'=>'USD',
                    'currencys'=>
                    [
                        'EUR'=>
                        [
                            'rate'=>0.93,
                            'symbol'=>'€',
                        ],
                        'USD'=>
                        [
                            'rate'=>1,
                            'symbol'=>'$',
                        ],
                        'GBP'=>
                        [
                            'rate'=>0.8,
                            'symbol'=>'£',
                        ],
                        'CNY'=>
                        [
                            'rate'=>6.3,
                            'symbol'=>'￥',
                        ],
                    ],
                ],
                'newsletter'=>
                [
                    'class'=>'fecshop\services\page\Newsletter',
                ],
                'staticblock'=>
                [
                    'class'=>'fecshop\services\page\StaticBlock',
                ],
                'menu'=>
                [
                    'class'=>'fecshop\services\page\Menu',
                    'displayHome'=>
                    [
                        'enable'=>true,
                        'display'=>'Home',
                    ],
                    'frontCustomMenu'=>
                    [

                    ],
                    'behindCustomMenu'=>
                    [
                        0=>
                        [
                            'name'=>'custom menu',
                            'urlPath'=>'/my-custom-menu.html',
                            'childMenu'=>
                            [
                                0=>
                                [
                                    'name'=>'my custom menu 2',
                                    'urlPath'=>'/my-custom-menu-2.html',
                                ],
                                1=>
                                [
                                    'name'=>'my custom menu 3',
                                    'urlPath'=>'/my-custom-menu-2.html',
                                    'childMenu'=>
                                    [
                                        0=>
                                        [
                                            'name'=>'my custom menu 3',
                                            'urlPath'=>'/my-custom-menu-2.html',
                                        ],
                                        1=>
                                        [
                                            'name'=>'my custom menu 3',
                                            'urlPath'=>'/my-custom-menu-2.html',
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'message'=>
                [
                    'class'=>'fecshop\services\page\Message',
                ],
                'trace'=>
                [
                    'class'=>'fecshop\services\page\Trace',
                    'traceJsEnable'=>false,
                    'website_id'=>'0c1b4947-38d0-4aa1-913e-455e2b78fbb0',
                    'access_token'=>'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3ZWJzaXRlX3VpZCI6IjBjMWI0OTQ3LTM4ZDAtNGFhMS05MTNlLTQ1NWUyYjc4ZmJiMCJ9.9HZJswnDA6pSSZnVB0wNSO_rUppRw1cFKzCR-m9BNAA',
                    'api_time_out'=>1.5,
                    'trace_url'=>'xx.fecshop.com/fec_trace.js',
                    'trace_api_url'=>'http://144.202.52.147:3000/fec/trace/api',
                ],
            ],
        ],
        'payment'=>
        [
            'class'=>'fecshop\services\Payment',
            'childService'=>
            [
                'paypal'=>
                [
                    'class'=>'fecshop\services\payment\Paypal',
                    'seller_email'=>'',
                    'express_payment_method'=>'paypal_express',
                    'standard_payment_method'=>'paypal_standard',
                    'version'=>'109.0',
                    'use_local_certs'=>false,
                    'crt_file'=>
                    [
                        'www.paypal.com'=>'@fecshop/services/payment/cert/paypal.crt',
                        'api-3t.paypal.com'=>'@fecshop/services/payment/cert/api-3tsandboxpaypalcom.crt',
                    ],
                ],
                'alipay'=>
                [
                    'class'=>'fecshop\services\payment\Alipay',
                    'format'=>'json',
                    'charset'=>'utf-8',
                    'signType'=>'RSA2',
                    'appId'=>'2016080500172713',
                    'sellerId'=>'2088102170055546',
                    'rsaPrivateKey'=>'MIIEpAIBAAKCAQEApIw+Hsk65Z+mieDsEiTkhtf7ZNBgks83DLUDb1yh2d/HDB0s9zHFzsgQGny0kUTM0fJ43h7WydyUG9Kuv4fxD5iVfM2xkUYW5bvfTXVaj5LLj8rTKL+nnFybzzM5rewqh2u1Gzd7BbpOnhMn4Y+7JyyaWXsnRFBxIrmRAqQJVlVUG4RclLHfplFkMVcEMzoRda2UV54oQDMg8ZxignCqxgIKr7bpwpgdpdqZArHtmyEjhQfIblCLDjVk0rKxGsaz+ATYVt3eQozdyNEuKFRhy0VGmwmdQYhQFbge7SS6bVqXZHsq2fNZ6hMJ2XNOZajFm5jXMksnaX85PzdJ58HFewIDAQABAoIBAAn/c27Pb0Kwdp/+CJn5n+EJkn7HonaJHKErBnBnwnXIgQGdbDQA1DICOehCF36UHZXME8f7O7W8L0uZe4Crs9vsu3h/zwAysAV5atH8BWqf0rqD6lyZeIepoNXwGNsWdGcSBkkHD/SDI2+7Xjr4TrjMnvw83V/rO1SOzd7JNMAICj6NZ2tteIqQCn+BriEEawRDimSAWvVaCbwnbCDF8y40MxZ4K6picBQ0gsbC6eQuXRqzB6CoFBkQsXGtK0VXvlJXVmKRzRqPxjD6Cer21tF1CDryVedSWKsdwEXvOdO8LdPZpnmQMvwyTuhM0V9L3rif4spIK9ML3lZLzM47rpECgYEA2XzyRUEni4jKmWcE3oSZjCvp5BJwi6DSRkAphGTwoW/8oTCJhx1B43Qusxv0bUwGzN/KlRHwgNRerQ9xqWMYnIIfBJLOqASunB8eHMBDN+zC6TnUKOu43CpZ+fGVVm2VUbWLHr5h93AOBSQhtvvegbEk9hbNRCCbcY6jbZZmgkUCgYEAwa9v5Bk8q0obGonDUd5LZkHBt7mfT12cUPkfBClz8/tpv7rirCg5I4XaQHerEo+iCOpn3iIl37ix6V7LcspjJuJwpTn0OzugO7MzEyRi0zAqkNAB1voeJL/hl08rHVkA9fZ2AVuOhUvG2A1pqB8BjY9AW1/2W/EXH16qCKzfhL8CgYEAjK/QoJAHHrH8LMOBWNf547y8bfanqwr7OspikOwi5Ktmhna5YBfC+Xm8g8w/jzww4fKaP1f9dbjrDZQB+IrL7uIVYoX8/J8avI88kWilktWrN+daoKXrTTBwR8jIy8HTZ6nCNr787G0mBJlc3duMEeUffbk+SyW0p/6XJVq3MOkCgYEAhXqPJOZTjkRS63YXels1ITKd+yzcYojDynX07xxWQcV4+l4kCrrprdZ4M8eEyRTdeUF59XcZHNYfHhJrKR/bNxgEw4luDEgqRBpaT43a4WonW4dOTUYv8eme4XT45I/K/rcsWgEr9ibj0U9lCizcGB+qHY7DrFc5NTA7BCGHJOcCgYAN82UigyX4qyqpQDofP/fQOybE2QJuG4pG3x3k/nMxCYm6DAcDS9WyRIAlNwOLXDFLICPa3SlaFjC4A0hLh1CU0465Bau+/q8Avs2/Hz1SMoeqyKf8Sq3RyCFFSb0Zsq26Tr8BtyRjHfFRDiZe5O9H7lOCGqiQEgUuAE9aCgCYVA==',
                    'alipayrsaPublicKey'=>'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt5egD1BQCK5fCQXKsgWh+VFj9zanV9cdwVmM/MOQ/zrwMBHMIRO0IdJMft351iXtyACKVX+noK1qzkiVOdg3MxLjbGoMDKR+/1PDxoxtWSVUJBywoYHH/Dh7TCi5GWGasOlXV4qWi0e5Yfa2x/Wi0cxqx76aY5izXEyabHAvWgTWNv121ZRNhl4qcuoWZYiMIQpTst6hEhRn/isUMgdtLRQ1a06q+qOkLmJ99vq8cqbfduAdOuhzbZNWqLV76CSc0meurlVtDoIn5kVAZdzjNTA2rlqSCgs/OZxaL8s/qrIynhLoB6U6i0fj4RsIsbrvoSnrPWo98rsM0RrlU8fpdwIDAQAB',
                    'gatewayUrl'=>'https://openapi.alipaydev.com/gateway.do',
                    'alipay_aop_sdk_work_dir'=>'/tmp',
                    'alipay_aop_sdk_dev_mode'=>true,
                    'devide'=>'pc',
                ],
                'wxpay'=>
                [
                    'class'=>'fecshop\services\payment\Wxpay',
                    'devide'=>'pc',
                    'configFile'=>'@common/config/payment/wxpay/lib/WxPay.Config.php',
                ],
            ],
            'noRelasePaymentMethod'=>
            [
                0=>'check_money',
            ],
            'paymentConfig'=>
            [
                'standard'=>
                [
                    'check_money'=>
                    [
                        'label'=>'Check / Money Order',
                        'supplement'=>'Off-line Money Payments',
                        'style'=>'<style></style>',
                        'start_url'=>'@homeUrl/payment/checkmoney/start',
                        'success_redirect_url'=>'@homeUrl/payment/success',
                    ],
                    'paypal_standard'=>
                    [
                        'start_url'=>'@homeUrl/payment/paypal/standard/start',
                        'nvp_url'=>'https://api-3t.sandbox.paypal.com/nvp',
                        'webscr_url'=>'https://www.sandbox.paypal.com/cgi-bin/webscr',
                        'account'=>'zqy234api1-facilitator_api1.126.com',
                        'password'=>'HF4TNTTXUD6YQREH',
                        'signature'=>'An5ns1Kso7MWUdW4ErQKJJJ4qi4-ANB-xrkMmTHpTszFaUx2v4EHqknV',
                        'label'=>'PayPal Express Payments',
                        'return_url'=>'@homeUrl/payment/paypal/standard/review',
                        'cancel_url'=>'@homeUrl/payment/paypal/standard/cancel',
                        'success_redirect_url'=>'@homeUrl/payment/success',
                        'ipn_url'=>'@homeUrl/payment/paypal/standard/ipn',
                    ],
                    'alipay_standard'=>
                    [
                        'label'=>'支付宝支付',
                        'start_url'=>'@homeUrl/payment/alipay/standard/start',
                        'return_url'=>'@homeUrl/payment/alipay/standard/review',
                        'ipn_url'=>'@homeUrl/payment/alipay/standard/ipn',
                        'success_redirect_url'=>'@homeUrl/payment/success',
                    ],
                    'wxpay_standard'=>
                    [
                        'label'=>'微信支付',
                        'start_url'=>'@homeUrl/payment/wxpay/standard/start',
                        'return_url'=>'@homeUrl/payment/wxpay/standard/review',
                        'ipn_url'=>'@homeUrl/payment/wxpay/standard/ipn',
                        'success_redirect_url'=>'@homeUrl/payment/success',
                    ],
                ],
                'express'=>
                [
                    'paypal_express'=>
                    [
                        'nvp_url'=>'https://api-3t.sandbox.paypal.com/nvp',
                        'webscr_url'=>'https://www.sandbox.paypal.com/cgi-bin/webscr',
                        'account'=>'zqy234api1-facilitator_api1.126.com',
                        'password'=>'HF4TNTTXUD6YQREH',
                        'signature'=>'An5ns1Kso7MWUdW4ErQKJJJ4qi4-ANB-xrkMmTHpTszFaUx2v4EHqknV',
                        'label'=>'PayPal Express Payments',
                        'return_url'=>'@homeUrl/payment/paypal/express/review',
                        'cancel_url'=>'@homeUrl/payment/paypal/express/cancel',
                        'success_redirect_url'=>'@homeUrl/payment/success',
                        'ipn_url'=>'@homeUrl/payment/paypal/express/ipn',
                    ],
                ],
            ],
        ],
        'product'=>
        [
            'class'=>'fecshop\services\Product',
            'categoryAggregateMaxCount'=>6000,
            'childService'=>
            [
                'image'=>
                [
                    'class'=>'fecshop\services\product\Image',
                    'imageFloder'=>'media/catalog/product',
                    'maxUploadMSize'=>5,
                ],
                'price'=>
                [
                    'class'=>'fecshop\services\product\Price',
                    'ifSpecialPriceGtPriceFinalPriceEqPrice'=>true,
                ],
                'review'=>
                [
                    'class'=>'fecshop\services\product\Review',
                    'filterByLang'=>false,
                    'reviewOnlyOrderedProduct'=>true,
                    'reviewMonth'=>6,
                ],
                'favorite'=>
                [
                    'class'=>'fecshop\services\product\Favorite',
                ],
                'info'=>
                [
                    'class'=>'fecshop\services\product\Info',
                ],
                'productapi'=>
                [
                    'class'=>'fecshop\services\product\ProductApi',
                ],
                'stock'=>
                [
                    'class'=>'fecshop\services\product\Stock',
                    'zeroInventory'=>0,
                ],
            ],
            'customAttrGroup'=>
            [
                'clothes_group'=>
                [
                    'spu_attr'=>
                    [
                        'color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'颜色',
                            'name'=>'color',
                            'showAsImg'=>true,
                            'sort_order'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'one-color'=>'one-color',
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                        'size'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'尺码',
                            'name'=>'size',
                            'sort_order'=>2,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'one-size'=>'one-size',
                                    'S'=>'S',
                                    'M'=>'M',
                                    'L'=>'L',
                                    'XL'=>'XL',
                                    'XXL'=>'XXL',
                                    'XXXL'=>'XXXL',
                                ],
                            ],
                        ],
                    ],
                    'general_attr'=>
                    [
                        'my_remark'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的备注',
                            'name'=>'my_remark',
                            'display'=>
                            [
                                'type'=>'inputString',
                            ],
                            'require'=>0,
                        ],
                        'my_email'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的邮箱',
                            'name'=>'my_email',
                            'require'=>0,
                            'display'=>
                            [
                                'type'=>'inputEmail',
                            ],
                        ],
                        'my_date'=>
                        [
                            'label'=>'我的日期',
                            'name'=>'my_date',
                            'display'=>
                            [
                                'type'=>'inputDate',
                            ],
                        ],
                        'style'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'类型',
                            'name'=>'style',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Casual'=>'Casual',
                                    'Cute'=>'Cute',
                                    'Sexy & Club'=>'Sexy & Club',
                                    'Bohemian'=>'Bohemian',
                                    'Vintage '=>'Vintage ',
                                    'Brief'=>'Brief',
                                    'Work'=>'Work',
                                    'Novelty'=>'Novelty',
                                ],
                            ],
                        ],
                        'dresses-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'裙长',
                            'name'=>'dresses-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Mini'=>'Mini',
                                    'Knee-Length'=>'Knee-Length',
                                    'Mid-Calf'=>'Mid-Calf',
                                    'Ankle-Length'=>'Ankle-Length',
                                    'Floor-Length '=>'Floor-Length ',
                                ],
                            ],
                        ],
                        'pattern-type'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'款式',
                            'name'=>'pattern-type',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Animal'=>'Animal',
                                    'Character'=>'Character',
                                    'Floral'=>'Floral',
                                    'Geometric '=>'Geometric ',
                                    'Leopard '=>'Leopard ',
                                    'Letter'=>'Letter',
                                    'Paisley'=>'Paisley',
                                    'Patchwork'=>'Patchwork',
                                    'Polka Dot'=>'Polka Dot',
                                    'Print'=>'Print',
                                    'Striped'=>'Striped',
                                ],
                            ],
                        ],
                        'sleeve-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'袖长',
                            'name'=>'sleeve-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Sleeveless'=>'Sleeveless',
                                    'Short-Sleeves'=>'Short Sleeves',
                                    'Half-Sleeves'=>'Half Sleeves',
                                    '3-4-Length-Sleeves '=>'3/4 Length Sleeves ',
                                    'Long-Sleeves '=>'Long Sleeves ',
                                ],
                            ],
                        ],
                        'collar'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'领口',
                            'name'=>'collar',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Round Neck'=>'Round Neck',
                                    'V-Neck'=>'V-Neck',
                                    'Hooded'=>'Hooded',
                                    'Turn-down-Collar'=>'Turn-down Collar',
                                ],
                            ],
                        ],
                    ],
                    'custom_options'=>
                    [
                        'my_color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Color',
                            'name'=>'color',
                            'showAsImg'=>true,
                            'require'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                        'my_size'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Size',
                            'name'=>'size',
                            'require'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'S'=>'S',
                                    'M'=>'M',
                                    '0.6'=>'0.6',
                                    'L'=>'L',
                                    'XL'=>'XL',
                                    'XXL'=>'XXL',
                                    'XXXL'=>'XXXL',
                                ],
                            ],
                        ],
                    ],
                ],
                'men_group'=>
                [
                    'spu_attr'=>
                    [
                        'color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'颜色',
                            'name'=>'color',
                            'showAsImg'=>true,
                            'sort_order'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'one-color'=>'one-color',
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                        'size'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'尺码',
                            'name'=>'size',
                            'sort_order'=>2,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'one-size'=>'one-size',
                                    'S'=>'S',
                                    'M'=>'M',
                                    'L'=>'L',
                                    'XL'=>'XL',
                                    'XXL'=>'XXL',
                                    'XXXL'=>'XXXL',
                                ],
                            ],
                        ],
                        'test3'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'测试3',
                            'name'=>'test3',
                            'sort_order'=>3,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    't_1'=>'t_1',
                                    't_2'=>'t_2',
                                    't_3'=>'t_3',
                                    't_4'=>'t_4',
                                ],
                            ],
                        ],
                    ],
                    'general_attr'=>
                    [
                        'my_remark'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的备注',
                            'name'=>'my_remark',
                            'display'=>
                            [
                                'type'=>'inputString',
                            ],
                            'require'=>0,
                        ],
                        'my_email'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的邮箱',
                            'name'=>'my_email',
                            'require'=>0,
                            'display'=>
                            [
                                'type'=>'inputEmail',
                            ],
                        ],
                        'my_date'=>
                        [
                            'label'=>'我的日期',
                            'name'=>'my_date',
                            'display'=>
                            [
                                'type'=>'inputDate',
                            ],
                        ],
                        'style'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'类型',
                            'name'=>'style',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Casual'=>'Casual',
                                    'Cute'=>'Cute',
                                    'Sexy & Club'=>'Sexy & Club',
                                    'Bohemian'=>'Bohemian',
                                    'Vintage '=>'Vintage ',
                                    'Brief'=>'Brief',
                                    'Work'=>'Work',
                                    'Novelty'=>'Novelty',
                                ],
                            ],
                        ],
                        'dresses-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'裙长',
                            'name'=>'dresses-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Mini'=>'Mini',
                                    'Knee-Length'=>'Knee-Length',
                                    'Mid-Calf'=>'Mid-Calf',
                                    'Ankle-Length'=>'Ankle-Length',
                                    'Floor-Length '=>'Floor-Length ',
                                ],
                            ],
                        ],
                        'pattern-type'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'款式',
                            'name'=>'pattern-type',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Animal'=>'Animal',
                                    'Character'=>'Character',
                                    'Floral'=>'Floral',
                                    'Geometric '=>'Geometric ',
                                    'Leopard '=>'Leopard ',
                                    'Letter'=>'Letter',
                                    'Paisley'=>'Paisley',
                                    'Patchwork'=>'Patchwork',
                                    'Polka Dot'=>'Polka Dot',
                                    'Print'=>'Print',
                                    'Striped'=>'Striped',
                                ],
                            ],
                        ],
                        'sleeve-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'袖长',
                            'name'=>'sleeve-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Sleeveless'=>'Sleeveless',
                                    'Short-Sleeves'=>'Short Sleeves',
                                    'Half-Sleeves'=>'Half Sleeves',
                                    '3-4-Length-Sleeves '=>'3/4 Length Sleeves ',
                                    'Long-Sleeves '=>'Long Sleeves ',
                                ],
                            ],
                        ],
                        'collar'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'领口',
                            'name'=>'collar',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Round Neck'=>'Round Neck',
                                    'V-Neck'=>'V-Neck',
                                    'Hooded'=>'Hooded',
                                    'Turn-down-Collar'=>'Turn-down Collar',
                                ],
                            ],
                        ],
                    ],
                    'custom_options'=>
                    [
                        'my_color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Color',
                            'name'=>'color',
                            'showAsImg'=>true,
                            'require'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                        'my_size'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Size',
                            'name'=>'size',
                            'require'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'S'=>'S',
                                    'M'=>'M',
                                    'L'=>'L',
                                    'XL'=>'XL',
                                    'XXL'=>'XXL',
                                    'XXXL'=>'XXXL',
                                ],
                            ],
                        ],
                    ],
                ],
                'computer_group'=>
                [
                    'spu_attr'=>
                    [
                        'xinghao'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'型号',
                            'name'=>'xinghao',
                            'showAsImg'=>true,
                            'sort_order'=>1,
                            'relateImage'=>true,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'xinghao1'=>'xinghao1',
                                    'xinghao2'=>'xinghao2',
                                    'xinghao3'=>'xinghao3',
                                ],
                            ],
                        ],
                        'cpu'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'cpu',
                            'name'=>'cpu',
                            'sort_order'=>2,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'cpu1'=>'cpu1',
                                    'cpu2'=>'cpu2',
                                    'cpu3'=>'cpu3',
                                ],
                            ],
                        ],
                    ],
                    'general_attr'=>
                    [
                        'memory_capacity'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'Memory Capacity',
                            'name'=>'memory_capacity',
                            'display'=>
                            [
                                'type'=>'inputString',
                                'lang'=>true,
                            ],
                            'require'=>0,
                        ],
                    ],
                    'custom_option_attr'=>
                    [
                        'color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'颜色',
                            'name'=>'color',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                    ],
                ],
                'test_group'=>
                [
                    'custom_options'=>
                    [
                        'my_color'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Color',
                            'name'=>'color',
                            'showAsImg'=>true,
                            'require'=>1,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'red'=>'red',
                                    'white'=>'white',
                                    'black'=>'black',
                                    'blue'=>'blue',
                                    'green'=>'green',
                                    'yellow'=>'yellow',
                                    'gray'=>'gray',
                                    'khaki'=>'khaki',
                                    'ivory'=>'ivory',
                                    'beige'=>'beige',
                                    'orange'=>'orange',
                                    'cyan'=>'cyan',
                                    'leopard'=>'leopard',
                                    'camouflage'=>'camouflage',
                                    'silver'=>'silver',
                                    'pink'=>'pink',
                                    'purple'=>'purple',
                                    'brown'=>'brown',
                                    'golden'=>'golden',
                                    'multicolor'=>'multicolor',
                                    'white & blue'=>'White & Blue',
                                    'white & black'=>'White & Black',
                                ],
                            ],
                        ],
                        'my_size'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Size',
                            'name'=>'size',
                            'require'=>1,
                            'showAsImg'=>false,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'S'=>'S',
                                    'M'=>'M',
                                    'L'=>'L',
                                    'XL'=>'XL',
                                    'XXL'=>'XXL',
                                    'XXXL'=>'XXXL',
                                ],
                            ],
                        ],
                        'my_size2'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Size',
                            'name'=>'size',
                            'require'=>1,
                            'showAsImg'=>false,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'S2'=>'S2',
                                    'M2'=>'M2',
                                    'L2'=>'L2',
                                    'XL2'=>'XL2',
                                    'XXL2'=>'XXL2',
                                    'XXXL2'=>'XXXL2',
                                ],
                            ],
                        ],
                        'my_size3'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'My Size',
                            'name'=>'size',
                            'require'=>1,
                            'showAsImg'=>false,
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'S3'=>'S3',
                                    'M3'=>'M3',
                                    'L3'=>'L3',
                                ],
                            ],
                        ],
                    ],
                    'general_attr'=>
                    [
                        'my_remark'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的备注',
                            'name'=>'my_remark',
                            'display'=>
                            [
                                'type'=>'inputString',
                            ],
                            'require'=>0,
                        ],
                        'my_email'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'我的邮箱',
                            'name'=>'my_email',
                            'require'=>0,
                            'display'=>
                            [
                                'type'=>'inputEmail',
                            ],
                        ],
                        'my_date'=>
                        [
                            'label'=>'我的日期',
                            'name'=>'my_date',
                            'display'=>
                            [
                                'type'=>'inputDate',
                            ],
                        ],
                        'style'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'类型',
                            'name'=>'style',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Casual'=>'Casual',
                                    'Cute'=>'Cute',
                                    'Sexy & Club'=>'Sexy & Club',
                                    'Bohemian'=>'Bohemian',
                                    'Vintage '=>'Vintage ',
                                    'Brief'=>'Brief',
                                    'Work'=>'Work',
                                    'Novelty'=>'Novelty',
                                ],
                            ],
                        ],
                        'dresses-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'裙长',
                            'name'=>'dresses-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Mini'=>'Mini',
                                    'Knee-Length'=>'Knee-Length',
                                    'Mid-Calf'=>'Mid-Calf',
                                    'Ankle-Length'=>'Ankle-Length',
                                    'Floor-Length '=>'Floor-Length ',
                                ],
                            ],
                        ],
                        'pattern-type'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'款式',
                            'name'=>'pattern-type',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Animal'=>'Animal',
                                    'Character'=>'Character',
                                    'Floral'=>'Floral',
                                    'Geometric '=>'Geometric ',
                                    'Leopard '=>'Leopard ',
                                    'Letter'=>'Letter',
                                    'Paisley'=>'Paisley',
                                    'Patchwork'=>'Patchwork',
                                    'Polka Dot'=>'Polka Dot',
                                    'Print'=>'Print',
                                    'Striped'=>'Striped',
                                ],
                            ],
                        ],
                        'sleeve-length'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'袖长',
                            'name'=>'sleeve-length',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Sleeveless'=>'Sleeveless',
                                    'Short-Sleeves'=>'Short Sleeves',
                                    'Half-Sleeves'=>'Half Sleeves',
                                    '3-4-Length-Sleeves '=>'3/4 Length Sleeves ',
                                    'Long-Sleeves '=>'Long Sleeves ',
                                ],
                            ],
                        ],
                        'collar'=>
                        [
                            'dbtype'=>'String',
                            'label'=>'领口',
                            'name'=>'collar',
                            'display'=>
                            [
                                'type'=>'select',
                                'data'=>
                                [
                                    'Round Neck'=>'Round Neck',
                                    'V-Neck'=>'V-Neck',
                                    'Hooded'=>'Hooded',
                                    'Turn-down-Collar'=>'Turn-down Collar',
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'search'=>
        [
            'class'=>'fecshop\services\Search',
            'childService'=>
            [
                'mongoSearch'=>
                [
                    'class'=>'fecshop\services\search\MongoSearch',
                    'enableService'=>true,
                    'searchIndexConfig'=>
                    [
                        'name'=>10,
                        'description'=>5,
                    ],
                    'searchLang'=>
                    [
                        'en'=>'english',
                        'fr'=>'french',
                        'de'=>'german',
                        'es'=>'spanish',
                        'ru'=>'russian',
                        'pt'=>'portuguese',
                    ],
                ],
                'xunSearch'=>
                [
                    'class'=>'fecshop\services\search\XunSearch',
                    'enableService'=>true,
                    'fuzzy'=>true,
                    'synonyms'=>true,
                    'searchLang'=>
                    [
                        'zh'=>'chinese',
                    ],
                ],
            ],
            'filterAttr'=>
            [
                0=>'color',
                1=>'size',
                2=>'color',
                3=>'size',
            ],
        ],
        'session'=>
        [
            'class'=>'fecshop\services\Session',
            'timeout'=>3600,
            'updateTimeLimit'=>600,
            'storage'=>'SessionRedis',
        ],
        'shipping'=>
        [
            'class'=>'fecshop\services\Shipping',
            'shippingCsvDir'=>'@common/config/shipping',
            'volumeWeightCoefficient'=>5000,
            'shippingConfig'=>
            [
                'free_shipping'=>
                [
                    'label'=>'Free shipping( 7-20 work days)',
                    'name'=>'HKBRAM',
                    'formula'=>'0',
                    'country'=>
                    [
                        'type'=>'allow',
                        'code'=>
                        [
                            0=>'CN',
                            1=>'US',
                        ],
                    ],
                    'weight'=>
                    [
                        'min'=>0,
                        'max'=>100,
                    ],
                ],
                'middle_shipping'=>
                [
                    'label'=>'middle shipping( 6-15 work days)',
                    'name'=>'HKBRAM',
                    'formula'=>'[weight] * 0.5',
                ],
                'fast_shipping'=>
                [
                    'label'=>'Fast Shipping( 5-10 work days)',
                    'name'=>'HKDHL',
                    'formula'=>'csv',
                    'csv_content'=>'',
                ],
            ],
        ],
        'sitemap'=>
        [
            'class'=>'fecshop\services\Sitemap',
        ],
        'store'=>
        [
            'class'=>'fecshop\services\Store',
            'stores'=>
            [
                'appfront.fecshoptest.com'=>
                [
                    'language'=>'en_US',
                    'languageName'=>'English',
                    'thirdThemeDir'=>
                    [

                    ],
                    'currency'=>'USD',
                    'mobile'=>
                    [
                        'enable'=>true,
                        'condition'=>
                        [
                            0=>'phone',
                            1=>'tablet',
                        ],
                        'redirectDomain'=>'apphtml5.fecshoptest.com',
                        'https'=>false,
                        'type'=>'appserver',
                    ],
                    'thirdLogin'=>
                    [
                        'facebook'=>
                        [
                            'facebook_app_id'=>'184963',
                            'facebook_app_secret'=>'2e097dd7139',
                        ],
                        'google'=>
                        [
                            'CLIENT_ID'=>'38037grhccontent.com',
                            'CLIENT_SECRET'=>'ei8RaoCHYm0rrwO',
                        ],
                    ],
                ],
                'appfront.fecshoptest.com/fr'=>
                [
                    'language'=>'fr_FR',
                    'languageName'=>'Fran?ais',
                    'localThemeDir'=>'@appfront/theme/terry/theme01',
                    'thirdThemeDir'=>
                    [

                    ],
                    'currency'=>'RMB',
                    'mobile'=>
                    [
                        'enable'=>true,
                        'condition'=>
                        [
                            0=>'phone',
                        ],
                        'redirectDomain'=>'apphtml5.fecshoptest.com/fr',
                    ],
                ],
                'appfront.fecshoptest.es'=>
                [
                    'language'=>'es_ES',
                    'languageName'=>'Espa?ol',
                    'localThemeDir'=>'@appfront/theme/terry/theme01',
                    'thirdThemeDir'=>
                    [

                    ],
                    'currency'=>'USD',
                    'mobile'=>
                    [
                        'enable'=>true,
                        'condition'=>
                        [
                            0=>'tablet',
                        ],
                        'redirectDomain'=>'fecshop.apphtml5.es.fancyecommerce.com',
                    ],
                ],
                'appfront.fecshoptest.com/cn'=>
                [
                    'language'=>'zh_CN',
                    'languageName'=>'中文',
                    'localThemeDir'=>'@appfront/theme/terry/theme01',
                    'thirdThemeDir'=>
                    [

                    ],
                    'currency'=>'RMB',
                    'mobile'=>
                    [
                        'enable'=>false,
                        'condition'=>
                        [
                            0=>'phone',
                            1=>'tablet',
                        ],
                        'redirectDomain'=>'fecshop.apphtml5.fancyecommerce.com/cn',
                    ],
                ],
            ],
        ],
        'systemhelper'=>
        [
            'class'=>'fecshop\services\Systemhelper',
        ],
        'url'=>
        [
            'class'=>'fecshop\services\Url',
            'showScriptName'=>false,
            'randomCount'=>8,
            'childService'=>
            [
                'rewrite'=>
                [
                    'class'=>'fecshop\services\url\Rewrite',
                    'storage'=>'RewriteMongodb',
                ],
                'category'=>
                [
                    'class'=>'fecshop\services\url\Category',
                ],
            ],
        ],
    ],
];